blog_frontend:
    resource: "@BlogFrontendBundle/Controller/"
    type:     annotation
    prefix:   /blog/frontend

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix: /blog

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
