blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix: /blog

app:
    resource: '@AppBundle/Controller/'
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
