blog:
    resource: "@BlogBackendBundle/Resources/config/routing.yml"
    prefix: /api

blog_frontend:
    resource: "@BlogFrontendBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
